export const mainData = [
    {
        image: "https://happyherbals.online/cdn/shop/products/hairpackpouch_1400x.png?v=1677666442",
        text: "Seedra Cilantro Seeds for Planting Indoor and Outdoor",
        price: "75",
        typeOfPlant: "HERBS",
        typeOfElement: "ANGELICA",
        seedType: "Hybrid",
        mainFeatures: "Drought Tolerant",
        sunlight: "Full Sun",
        id: "05695843",
        qty: 1
    },
    {
        image: "https://mobileimages.lowes.com/productimages/1bd5a4f3-2cb8-4dad-99bc-03cf9d9811da/16863459.jpg",
        text: "Seedra Ferry-Morse Seeds for Planting Indoor and Outdoor",
        price: "65",
        typeOfPlant: "FLOWERS",
        typeOfElement: "ROSE",
        seedType: "Open Pollinated",
        mainFeatures: "Extended Bloom Time",
        sunlight: "Full Sun",
        id: "320494"
    },
    {
        image: "https://happyherbals.online/cdn/shop/products/hairpackpouch_1400x.png?v=1677666442",
        text: "SEEDRA Spinach Seeds for Indoor and Outdoor Planting",
        price: "70",
        typeOfPlant: "HERBS",
        typeOfElement: "ANGELICA",
        seedType: "Hybrid",
        mainFeatures: "Attracts Pollinators",
        sunlight: "Full Sun",
        id: "091438835"
    },
    {
        image: "https://images.uzum.uz/cj0j25b6edfostijsb4g/original.jpg",
        text: "SEEDRA Parsley Seeds for Indoor and Outdoor Planting",
        price: "52",
        typeOfPlant: "VEGETABLES",
        typeOfElement: "CARROTS",
        seedType: "Open Pollinated",
        mainFeatures: "Air Purification",
        sunlight: "Full Sun",
        id: "828372910"
    },
    {
        image: "https://5.imimg.com/data5/YY/VM/DB/SELLER-6541824/9000-hybrid-maize-seeds.jpg",
        text: "SEEDRA Corn - Bodacious Hybrid Seeds for Indoor and Outdoor Planting",
        price: "35",
        typeOfPlant: "GRAINS",
        typeOfElement: "WHEAT",
        seedType: "Organic",
        mainFeatures: "High Germination Rate",
        sunlight: "Full Shade",
        id: "283791"
    },
    {
        image: "https://happyherbals.online/cdn/shop/products/hairpackpouch_1400x.png?v=1677666442",
        text: "SEEDRA SpearMint Seeds for Indoor and Outdoor Planting",
        price: "60",
        typeOfPlant: "HERBS",
        typeOfElement: "CALENDULA",
        seedType: "Pelleted",
        mainFeatures: "Drought Tolerant",
        sunlight: "Partial Shade",
        id: "72613894"
    },
    {
        image: "https://happyherbals.online/cdn/shop/products/hairpackpouch_1400x.png?v=1677666442",
        text: "Seedra Cilantro Seeds for Planting Indoor and Outdoor",
        price: "80",
        typeOfPlant: "HERBS",
        typeOfElement: "ANGELICA",
        seedType: "Pelleted",
        mainFeatures: "High Germination Rate",
        sunlight: "Full Shade",
        id: "5167834"
    },
    {
        image: "https://mobileimages.lowes.com/productimages/1bd5a4f3-2cb8-4dad-99bc-03cf9d9811da/16863459.jpg",
        text: "Seedra Ferry-Morse Seeds for Planting Indoor and Outdoor",
        price: "43",
        typeOfPlant: "FLOWERS",
        typeOfElement: "TULIPS",
        seedType: "Organic",
        mainFeatures: "Air Purification",
        sunlight: "Full Shade",
        id: "415253892"
    },
    {
        image: "https://happyherbals.online/cdn/shop/products/hairpackpouch_1400x.png?v=1677666442",
        text: "SEEDRA Sweet Marjor Seeds for Indoor and Outdoor Planting",
        price: "66",
        typeOfPlant: "HERBS",
        typeOfElement: "CALENDULA",
        seedType: "Pelleted",
        mainFeatures: "Attracts Pollinators",
        sunlight: "Full Shade",
        id: "218834904"
    },
    {
        image: "https://images.uzum.uz/cj0j25b6edfostijsb4g/original.jpg",
        text: "SEEDRA Parsley Seeds for Indoor and Outdoor Planting",
        price: "58",
        typeOfPlant: "VEGETABLES",
        typeOfElement: "POTATOS",
        seedType: "Open Pollinated",
        mainFeatures: "Extended Bloom Time",
        sunlight: "Full Shade",
        id: "931401458"
    },
    {
        image: "https://happyherbals.online/cdn/shop/products/hairpackpouch_1400x.png?v=1677666442",
        text: "Seedra Cilantro Seeds for Planting Indoor and Outdoor",
        price: "68",
        typeOfPlant: "HERBS",
        typeOfElement: "ANGELICA",
        seedType: "Organic",
        mainFeatures: "Drought Tolerant",
        sunlight: "Partial Shade",
        id: "1929030447"
    },
    {
        image: "https://5.imimg.com/data5/SELLER/Default/2021/6/BB/GN/TA/2486200/sweety-f-1-hybrid-sweet-corn-seeds-500x500.png",
        text: "SEEDRA Corn - Ferry-Morse Hybrid Seeds for Indoor and Outdoor Planting",
        price: "35",
        typeOfPlant: "GRAINS",
        typeOfElement: "CORN",
        seedType: "Hybrid",
        mainFeatures: "Drought Tolerant",
        sunlight: "Partial Shade",
        id: "34245"
    },
    {
        image: "https://images.uzum.uz/cj0j25b6edfostijsb4g/original.jpg",
        text: "SEEDRA Parsley Seeds for Indoor and Outdoor Planting",
        price: "52",
        typeOfPlant: "VEGETABLES",
        typeOfElement: "CARROTS",
        seedType: "Open Pollinated",
        mainFeatures: "Extended Bloom Time",
        sunlight: "Partial Sun",
        id: "28284940044"
    },
    {
        image: "https://happyherbals.online/cdn/shop/products/hairpackpouch_1400x.png?v=1677666442",
        text: "SEEDRA Parsley Seeds for Indoor and Outdoor Planting",
        price: "52",
        typeOfPlant: "HERBS",
        typeOfElement: "CALENDULA",
        seedType: "Organic",
        mainFeatures: "Attracts Pollinators",
        sunlight: "Partial Sun",
        id: "1029474"
    },
    {
        image: "https://mobileimages.lowes.com/productimages/1bd5a4f3-2cb8-4dad-99bc-03cf9d9811da/16863459.jpg",
        text: "Seedra Ferry-Morse Seeds for Planting Indoor and Outdoor",
        price: "88",
        typeOfPlant: "FLOWERS",
        typeOfElement: "ROSE",
        seedType: "Pelleted",
        mainFeatures: "Air Purification",
        sunlight: "Partial Sun",
        id: "120397646"
    },
    {
        image: "https://images.uzum.uz/cj0j25b6edfostijsb4g/original.jpg",
        text: "SEEDRA Parsley Seeds for Indoor and Outdoor Planting",
        price: "55",
        typeOfPlant: "VEGETABLES",
        typeOfElement: "POTATOES",
        seedType: "Organic",
        mainFeatures: "High Germination Rate",
        sunlight: "Partial Shade",
        id: "01928337465"
    },
    {
        image: "https://mobileimages.lowes.com/productimages/1bd5a4f3-2cb8-4dad-99bc-03cf9d9811da/16863459.jpg",
        text: "Seedra Ferry-Morse Seeds for Planting Indoor and Outdoor",
        price: "90",
        typeOfPlant: "FLOWERS",
        typeOfElement: "TULIPS",
        seedType: "Open Pollinated",
        mainFeatures: "Drought Tolerant",
        sunlight: "Partial Shade",
        id: "93884161793"
    }
]